---
# tasks file for docker

- name: Instalando dependencias do docker engine
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Incluindo a chave do repositorio
  apt_key: url="https://download.docker.com/linux/ubuntu/gpg" state=present

- name: Incluir o repositorio do docker-engine
  apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present

- name: Intalando o docker engine
  apt: name=docker-ce update_cache=yes state=present

